package com.devmobile.cs2.esi_lib;

import android.app.FragmentManager;
import android.os.Bundle;
import android.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ListView;

import com.devmobile.cs2.esi_lib.Adapters.LivreAdapter;
import com.devmobile.cs2.esi_lib.Models.Livre;

public class ListeLivresFragement extends Fragment {

    private Livre[] livre_math;
    private Livre[] livre_elec;
    private Livre[] livre_algo;
    private Livre[] livre_base;
    private Livre[] livre_si;
    private Livre[] livre_tous;
    private Livre[] livre_affiche;
    private int numCateg = 0;
    public View fragmentView;
    ListView listLivreView;

    public ListeLivresFragement() {

    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (getArguments() != null) {
            String stcateg = getArguments().getString("categ");
            numCateg = Integer.parseInt(stcateg);
        }
        fragmentView = inflater.inflate(R.layout.liste_livres_fragement, container, false);
        return fragmentView;
    }

    @Override
    public void onStart() {
        super.onStart();
        init_data();
        switch (numCateg) {
            case 0:
                livre_affiche = livre_tous;
                break;
            case 1:
                livre_affiche = livre_math;
                break;
            case 2:
                livre_affiche = livre_elec;
                break;
            case 3:
                livre_affiche = livre_algo;
                break;
            case 4:
                livre_affiche = livre_base;
                break;
            case 5:
                livre_affiche = livre_si;
                break;
        }
        LivreAdapter adapter = new LivreAdapter(getActivity(), R.layout.liste_livres_range, livre_affiche);
        // ListView listLivreView = (ListView) getActivity().findViewById(R.id.listLivreView);
        //  ListView listLivreView = (ListView) ListeLivres.fragmentListeLivres.getActivity().findViewById(R.id.listLivreView);
        listLivreView = (ListView) fragmentView.findViewById(R.id.listLivre);
        listLivreView.setAdapter(adapter);
        listLivreView.setOnItemClickListener(new ListLivreClickListener());

    }

    private class ListLivreClickListener implements ListView.OnItemClickListener {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position,
                                long id) {
            // display view for selected nav drawer item
            displayDetailLivre(position);
        }

        private void displayDetailLivre(int position) {
           /* listLivreView.setItemChecked(position,true);
            listLivreView.setSelection(position);*/
            // update the main content by replacing fragments
            Fragment fragment = null;
            Bundle bundle = new Bundle();
            bundle.putString("image", ((Integer) livre_affiche[position].getImage()).toString());
            bundle.putString("titre", livre_affiche[position].getTitre());
            bundle.putString("auteur", livre_affiche[position].getAuteur());
            bundle.putString("categorie", livre_affiche[position].getCategorie());
            bundle.putString("annee", livre_affiche[position].getAnnee());
            bundle.putString("description", livre_affiche[position].getDescreption());
            ListeLivres.fragmentDetailLivre = new DetailLivreFragement();
            ListeLivres.fragmentDetailLivre.setArguments(bundle);
            if (ListeLivres.fragmentDetailLivre != null) {
                FragmentManager fragmentManager = getFragmentManager();

                if (!ListeLivres.isPhone && ListeLivres.isLand) {
                    // Log.e("landscape", "rahi landscape") ;
                    fragmentManager.beginTransaction()
                            .replace(R.id.frame_container2, ListeLivres.fragmentDetailLivre).commit();
                } else {
                    // Log.e("landscape", "rahi mahihce landscape") ;
                    fragmentManager.beginTransaction()
                            .replace(R.id.frame_container, ListeLivres.fragmentDetailLivre).commit();
                    ;
                }

            } else {
                // error in creating fragment
                Log.e("MainActivity", "Error in creating fragment detailLivreFragment");
            }
        }
    }

    public void init_data() {


        livre_math = new Livre[]
                {
                        new Livre(R.drawable.math1, "Analyse numérique", "Eric Canon", "Mathématique", "2012", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math2, "Statistiques descriptives", "Luc Lasn", "Mathématique", "2015 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math3, "Initiation à l'analyse mathématique", "André Giroux", "Mathématique", "2015", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math4, "Equations différentielles ordinaires", " Ahmed Lesfari", "Mathématique", "2015", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math5, "Probabilités et statistiques appliquées", "Pierre Dreyfuss", "Mathématique", "2004", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math6, "La logique", "Gilles Dowek", "Mathématique", "2003", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math7, "Statistiques en sciences humaines avec R", "Jean-Herman Guay", "Mathématique", "2010", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math8, "Mathématiques - 1res ES-L", "Thomas Petit", "Mathématique", "1999", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math9, "Processus stochastiques", "Sabin Lessard", "Mathématique", "2004", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math10, "La maison des mathématiques", "Cédric Villani", "Mathématique", "2003 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                };
        livre_elec = new Livre[]
                {
                        new Livre(R.drawable.elec1, "Les convertisseurs de l'électronique", "Guy Séguier", "Electronique", "2012", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec2, "Bases de l'électronique analogique", "Laurent Pichon", "Electronique", "2015", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec3, "Le grand livre d'Arduino", "Erik Bartmann", "Electronique", "2003", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec4, "Electronique de puissance", "Luc Lasne", "Electronique", "2004", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec5, "Communications sur fibres optiques", "Pierre Lecoy", "Electronique", "2010", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec6, "Réparez vous-même vos appareils électroniques", "Jean Boyer", "Electronique", "2000", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec7, "Optoélectronique appliquée", "Yannick Deshayes", "Electronique", "2001", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec8, "Raspberry Pi", "Maartje Jansee", "Electronique", "1999", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec9, "Electrochimie", "Fabien Miomandre", "Electronique", "2002", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec10, "L'électronique pour les nuls", "Gordon McComb", "Electronique", "1998", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                };
        livre_algo = new Livre[]
                {
                        new Livre(R.drawable.algo1, "Construire des robots très simples", "H. Katzenmaier", "Algorithmique", "2000", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo2, "Algorithmique", "Collectif Dunod", "Algorithmique", "2001", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo3, "Algorithmique et programmation en Java", "Vincent Granet", "Algorithmique", "2015", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo4, "Programmer pour les nuls", "Wallace Wang", "Algorithmique", "2012", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo5, "L'intelligence artificielle pour les développeurs", " Virginie Mathivet", "Algorithmique", "2013", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo6, "Cours d'algèbre et d'algorithmique", "Pierre Meunier", "Algorithmique", "2004", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo7, "Mathématiques et informatique", "Collectif Tangente", "Algorithmique", "2000", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo8, "Initiation à l'algorithmique et à la programmation en C", "Rita Zrour", "Algorithmique", "2009", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo9, "Techniques fondamentales de programmation", "Sébastien Rohaut", "Algorithmique", "1992", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo10, "Algorithmes et théorie des nombres", "Pierre Audibert", "Algorithmique", "1999", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                };
        livre_base = new Livre[]
                {
                        new Livre(R.drawable.base1, "Les bases de données NoSQL", " Rudi Bruchez", "Base de donnée", "1999", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base2, "Merise", "Jean-Luc Baptiste", "Base de donnée", "2004", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base3, "UML et XML pour le commerce électronique", "Odile Troulet-Lambert", "Base de donnée", "2005", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base4, "SQL pour Oracle", "Christian Soutou", "Base de donnée", "2013", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base5, "PostgreSQL", " Sébastien Lardière", "Base de donnée", "2015", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base6, "Access 2013", "Pierre Rigollet", "Base de donnée", "2003", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base7, "SQL Server 2014", "Olivier Maitre", "Base de donnée", "2015", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base8, "Oracle 12c", "Olivier Heurtel", "Base de donnée", "2003", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base9, "Big Data et Machine Learning", "Marc Batty", "Base de donnée", "1994", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base10, "Apprentissage machine", "Massih-Reza Amini", "Base de donnée", "1997", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                };

        livre_si = new Livre[]
                {
                        new Livre(R.drawable.si1, "Ingénierie des exigences", "Stéphane Badreau", "Système d'information", "2004", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si2, "Processus métiers et S.I.", "Chantal Morley", "Système d'information", "2005", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si3, "Expression des besoins pour le SI", "Yves Constantinidis", "Système d'information", "2003", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si4, "Business Intelligence et management", "Alphonse Carlier", "Système d'information", "2005", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si5, "Management des systèmes d'information", "Sylvie Gerbaix, Marc Pasquet", "Système d'information", "2009", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si6, "Business intelligence", "Jean-Pierre Girardot", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si7, "Optimiser l'organisation informatique de la PME", "Yves Le Dain", "Système d'information", "1990", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si8, "Yves Le Dain", "Oihab Allal-Chérif", "Système d'information", "2013", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si9, "Objectif Cloud", "Jean-Louis Caire", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si10, "Le cloud computing", "Bénédicte Fauvarque", "Système d'information", "19964", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                };

        livre_tous = new Livre[]
                {new Livre(R.drawable.math1, "Analyse numérique", "Eric Canon", "Mathématique", "2012", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math2, "Statistiques descriptives", "Luc Lasn", "Mathématique", "2015 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math3, "Initiation à l'analyse mathématique", "André Giroux", "Mathématique", "2015", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math4, "Equations différentielles ordinaires", " Ahmed Lesfari", "Mathématique", "2015", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math5, "Probabilités et statistiques appliquées", "Pierre Dreyfuss", "Mathématique", "2004", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math6, "La logique", "Gilles Dowek", "Mathématique", "2003", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math7, "Statistiques en sciences humaines avec R", "Jean-Herman Guay", "Mathématique", "2010", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math8, "Mathématiques - 1res ES-L", "Thomas Petit", "Mathématique", "1999", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math9, "Processus stochastiques", "Sabin Lessard", "Mathématique", "2004", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.math10, "La maison des mathématiques", "Cédric Villani", "Mathématique", "2003 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés"),
                        new Livre(R.drawable.elec1, "Les convertisseurs de l'électronique", "Guy Séguier", "Electronique", "2012", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec2, "Bases de l'électronique analogique", "Laurent Pichon", "Electronique", "2015", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec3, "Le grand livre d'Arduino", "Erik Bartmann", "Electronique", "2003", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec4, "Electronique de puissance", "Luc Lasne", "Electronique", "2004", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec5, "Communications sur fibres optiques", "Pierre Lecoy", "Electronique", "2010", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec6, "Réparez vous-même vos appareils électroniques", "Jean Boyer", "Electronique", "2000", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec7, "Optoélectronique appliquée", "Yannick Deshayes", "Electronique", "2001", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec8, "Raspberry Pi", "Maartje Jansee", "Electronique", "1999", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec9, "Electrochimie", "Fabien Miomandre", "Electronique", "2002", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.elec10, "L'électronique pour les nuls", "Gordon McComb", "Electronique", "1998", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi"),
                        new Livre(R.drawable.algo1, "Construire des robots très simples", "H. Katzenmaier", "Algorithmique", "2000", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo2, "Algorithmique", "Collectif Dunod", "Algorithmique", "2001", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo3, "Algorithmique et programmation en Java", "Vincent Granet", "Algorithmique", "2015", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo4, "Programmer pour les nuls", "Wallace Wang", "Algorithmique", "2012", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo5, "L'intelligence artificielle pour les développeurs", " Virginie Mathivet", "Algorithmique", "2013", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo6, "Cours d'algèbre et d'algorithmique", "Pierre Meunier", "Algorithmique", "2004", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo7, "Mathématiques et informatique", "Collectif Tangente", "Algorithmique", "2000", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo8, "Initiation à l'algorithmique et à la programmation en C", "Rita Zrour", "Algorithmique", "2009", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo9, "Techniques fondamentales de programmation", "Sébastien Rohaut", "Algorithmique", "1992", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.algo10, "Algorithmes et théorie des nombres", "Pierre Audibert", "Algorithmique", "1999", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème."),
                        new Livre(R.drawable.base1, "Les bases de données NoSQL", " Rudi Bruchez", "Base de donnée", "1999", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base2, "Merise", "Jean-Luc Baptiste", "Base de donnée", "2004", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base3, "UML et XML pour le commerce électronique", "Odile Troulet-Lambert", "Base de donnée", "2005", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base4, "SQL pour Oracle", "Christian Soutou", "Base de donnée", "2013", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base5, "PostgreSQL", " Sébastien Lardière", "Base de donnée", "2015", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base6, "Access 2013", "Pierre Rigollet", "Base de donnée", "2003", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base7, "SQL Server 2014", "Olivier Maitre", "Base de donnée", "2015", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base8, "Oracle 12c", "Olivier Heurtel", "Base de donnée", "2003", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base9, "Big Data et Machine Learning", "Marc Batty", "Base de donnée", "1994", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.base10, "Apprentissage machine", "Massih-Reza Amini", "Base de donnée", "1997", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé."),
                        new Livre(R.drawable.si1, "Ingénierie des exigences", "Stéphane Badreau", "Système d'information", "2004", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si2, "Processus métiers et S.I.", "Chantal Morley", "Système d'information", "2005", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si3, "Expression des besoins pour le SI", "Yves Constantinidis", "Système d'information", "2003", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si4, "Business Intelligence et management", "Alphonse Carlier", "Système d'information", "2005", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si5, "Management des systèmes d'information", "Sylvie Gerbaix, Marc Pasquet", "Système d'information", "2009", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si6, "Business intelligence", "Jean-Pierre Girardot", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si7, "Optimiser l'organisation informatique de la PME", "Yves Le Dain", "Système d'information", "1990", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si8, "Yves Le Dain", "Oihab Allal-Chérif", "Système d'information", "2013", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si9, "Objectif Cloud", "Jean-Louis Caire", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                        new Livre(R.drawable.si10, "Le cloud computing", "Bénédicte Fauvarque", "Système d'information", "19964", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence."),
                };

    }
}